FROM mysql

ENV MYSQL_ROOT_PASSWORD password
ENV MYSQL_DATABASE users

COPY /scripts/createTable.sql /docker-entrypoint-initdb.d/createTable.sql
COPY /scripts/insertUser.sql /docker-entrypoint-initdb.d/inserUser.sql
