version: '2.2'
services:
  app:
    image: ferwguerra/hello-world:latest
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: ferwguerra/my_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: