version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    #image: ferwguerra/hello-world
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: Dockerfile_db
    #image: ferwguerra/my_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'users'
      MYSQL_ROOT_PASSWORD: 'dont12hack34me56'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: