version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: '${AWS_ECR_ACCOUNT_URL}'
          repo: '${AWS_ECR_REPO}'
          region: '${AWS_REGION}'
          tag: '${AWS_ECR_TAG}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: '${AWS_REGION}'
          family: 'app-service-fargate'
          cluster-name: 'app-cluster'
          container-image-name-updates: 'container=app-container,tag=app'